// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Board struct {
	ID        int32
	Name      string
	OwnerID   int32
	CreatedAt pgtype.Timestamp
}

type BoardMember struct {
	BoardID int32
	UserID  int32
	Role    string
}

type Card struct {
	ID          int32
	ListID      int32
	Title       string
	Description pgtype.Text
	Position    int32
	CreatedAt   pgtype.Timestamp
}

type List struct {
	ID        int32
	BoardID   int32
	Title     string
	Position  int32
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID           int32
	Name         string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
}
